server:
  port: 8081

spring:
  application:
    name: new-process-camunda
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=new_schema
    username: admin
    password: admin
  sql:
    init:
      mode: always
  jpa:
    database: postgresql
    open-in-view: false
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
  flyway:
    schemas: new_schema
    baseline-on-migrate: true
    locations: db/migration

feign:
  client:
    config:
      workflow-client:
        url: "http://localhost:8082"
        connectTimeout: 5000
        readTimeout: 5000

camunda:
  bpm:
    client:
      base-url: "http://localhost:8082/rest"
      lock-duration: "1000"
      basic-auth:
        username: a
        password: a